[project]
name = "wafer-defects"
version = "0.1.0"
description = "Download and work with WM-811K wafer map dataset"
readme = "README.md"
requires-python = ">=3.10,<3.14"
dependencies = [
    "numpy>=1.26",
    "pandas==2.3.3",
    "matplotlib>=3.8",
    "seaborn>=0.13.2",
    "torch==2.10.0",
    "torchvision==0.25.0",
    "Pillow>=10.0",
    "tqdm>=4.67.3",
    "scikit-learn>=1.7.2",
    "certifi>=2026.1.4",
    "xgboost>=3.2.0",
    "umap-learn>=0.5.12",
    "kagglehub>=1.0.0",
    "scikit-image>=0.25.2",
    "ipykernel>=7.2.0",
]

[tool.uv]
dev-dependencies = [
    "jupyter>=1.1",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu", marker = "sys_platform == 'darwin'" },
    { index = "pytorch-cuda", marker = "sys_platform != 'darwin'" },
]
torchvision = [
    { index = "pytorch-cpu", marker = "sys_platform == 'darwin'" },
    { index = "pytorch-cuda", marker = "sys_platform != 'darwin'" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cuda"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
